services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - path: .env
        required: false
    environment:
      APP_ENV: development
      BOT_POLLING_ENABLED: "True"
      BOT_WEBHOOK_ENABLED: "False"
    volumes:
      - ./app:/app/app
      - ./tests:/app/tests
    command: ["python", "-m", "app.main"]
